spring:
  ai:
    ollama:
      base-url: https://ollama.com
      api-key: ${OLLAMA_API_KEY}
      chat:
        options:
          model: gpt-oss:120b
  application:
    name: AI Newsletter
news:
  aggregation:
    limit-days: 7

logging:
  level:
    org.example: DEBUG


